In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
import keras

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Dense, Flatten
from keras.utils import to_categorical

이미지 불러와서 numpy로 바꾸기

In [ ]:
img_dir = './images'
categories = os.listdir(img_dir)
nb_classes= len(categories)


In [58]:
#keras로 이미지 불러오기 
from keras.preprocessing.image import img_to_array, load_img, array_to_img


#음식 데이터 to numpy  , Label = 0
data_fd = []
data_fd_label = []
for num in range(1,501):
    #classes = ['exterior', 'interior','food']
    image_file = './images/{}{}.jpg'.format('food', num)
    image_array = img_to_array(load_img(image_file))
    #print(image_array)
    
    data_fd.append(image_array)
    data_fd_label.append(0)

data_fd = np.array(data_fd)
data_fd[-1]

array([[[ 59.,  31.,  19.],
        [ 60.,  32.,  20.],
        [ 61.,  33.,  21.],
        ...,
        [ 80.,  48.,  27.],
        [ 79.,  47.,  26.],
        [ 78.,  46.,  25.]],

       [[ 59.,  31.,  19.],
        [ 60.,  32.,  20.],
        [ 61.,  33.,  21.],
        ...,
        [ 80.,  48.,  27.],
        [ 79.,  47.,  26.],
        [ 78.,  46.,  25.]],

       [[ 60.,  32.,  20.],
        [ 60.,  32.,  20.],
        [ 61.,  33.,  21.],
        ...,
        [ 79.,  47.,  26.],
        [ 78.,  46.,  25.],
        [ 78.,  46.,  25.]],

       ...,

       [[113., 116., 105.],
        [114., 117., 106.],
        [108., 114., 104.],
        ...,
        [ 94.,  67.,  48.],
        [ 96.,  69.,  50.],
        [ 95.,  68.,  49.]],

       [[126., 129., 118.],
        [133., 139., 127.],
        [130., 136., 124.],
        ...,
        [ 98.,  71.,  52.],
        [100.,  73.,  54.],
        [ 99.,  72.,  53.]],

       [[133., 136., 125.],
        [140., 143., 132.],
        [133., 1

In [59]:
#실내 데이터 to numpy  , Label = 1

data_in = []
data_in_label = []
for num in range(1,501):
    #classes = ['exterior', 'interior','food']
    image_file = './images/{}{}.jpg'.format('interior', num)
    image_array = img_to_array(load_img(image_file))
    #print(image_array)
    
    data_in.append(image_array)
    data_in_label.append(1)

data_in = np.array(data_in)
data_in[-1]

array([[[45.,  0., 20.],
        [45.,  4., 22.],
        [45.,  4., 22.],
        ...,
        [67.,  6., 37.],
        [75.,  5., 39.],
        [81.,  1., 38.]],

       [[50.,  1., 22.],
        [47.,  2., 22.],
        [46.,  3., 22.],
        ...,
        [70.,  5., 37.],
        [74.,  4., 38.],
        [77.,  3., 38.]],

       [[55.,  0., 23.],
        [49.,  0., 21.],
        [48.,  0., 20.],
        ...,
        [72.,  1., 35.],
        [70.,  0., 34.],
        [71.,  1., 35.]],

       ...,

       [[79.,  2., 36.],
        [79.,  2., 36.],
        [79.,  2., 36.],
        ...,
        [24.,  0., 16.],
        [24.,  0., 14.],
        [24.,  0., 14.]],

       [[81.,  1., 36.],
        [79.,  2., 36.],
        [79.,  2., 36.],
        ...,
        [24.,  0., 16.],
        [22.,  0., 15.],
        [23.,  1., 14.]],

       [[79.,  2., 36.],
        [79.,  2., 36.],
        [79.,  2., 38.],
        ...,
        [30.,  3., 20.],
        [27.,  3., 19.],
        [26.,  2., 16.]]

In [60]:
#실외 데이터 to numpy  , Label = 2
data_ex= []
data_ex_label= []
for num in range(1,501):
    #classes = ['exterior', 'interior','food']
    image_file = './images/{}{}.jpg'.format('exterior', num)
    image_array = img_to_array(load_img(image_file))
    #print(image_array)
    
    data_ex.append(image_array)
    data_ex_label.append(2)

data_ex = np.array(data_ex)
data_ex[-1]

array([[[ 9., 12., 21.],
        [ 9., 12., 21.],
        [ 9., 12., 21.],
        ...,
        [ 5.,  9.,  8.],
        [ 5.,  9.,  8.],
        [ 5.,  9.,  8.]],

       [[ 9., 12., 21.],
        [ 9., 12., 21.],
        [ 9., 12., 21.],
        ...,
        [ 5.,  9.,  8.],
        [ 5.,  9.,  8.],
        [ 5.,  9.,  8.]],

       [[11., 11., 21.],
        [11., 11., 21.],
        [ 9., 12., 21.],
        ...,
        [ 5.,  9.,  8.],
        [ 5.,  9.,  8.],
        [ 5.,  9.,  8.]],

       ...,

       [[31., 18.,  9.],
        [31., 18.,  9.],
        [32., 19., 10.],
        ...,
        [53., 37., 21.],
        [53., 37., 21.],
        [53., 37., 21.]],

       [[31., 18.,  9.],
        [32., 19., 10.],
        [32., 19., 10.],
        ...,
        [53., 37., 21.],
        [54., 38., 22.],
        [55., 39., 23.]],

       [[32., 19., 10.],
        [32., 19., 10.],
        [33., 20., 11.],
        ...,
        [54., 38., 22.],
        [56., 40., 24.],
        [58., 42., 26.]]

In [73]:
train_test_split = 0.85

train_data_fd = int(len(data_fd)*train_test_split)
train_data_in = int(len(data_in)*train_test_split)
train_data_ex = int(len(data_ex)*train_test_split)


data_set = np.concatenate((data_fd, data_in, data_ex))
print(data_set.shape)
1500*0.85

(1497, 300, 300, 3)


In [ ]:
def plot_loss_curve(history):
    plt.figure(figsize = (5,3))
    
    plt.plot(history['loss'])
    plt.plot(history['val_loss'])
    
    plt.title('model loss')
    plt.xlabel('epoch')
    plt.ylabel('loss')
    plt.legend(['train','test'], loc = 'upper right')
    plt.show
    

모델링

In [ ]:

def train_mnist_model():
    (X_train, y_train), (X_test, y_test) = ************데이터 어떻게 불러올거야? 
    
    '''
    print("X_train.shape=", X_train.shape)
    print("y_train.shape", y_train.shape)
    
    print("X_test.shape=", X_test.shape)
    print("y_test.shape", y_test.shape)
    
    print(y_train[1])
    plt.imshow(X_train[1], cmap='gray')
    '''

 
    X_train = X_train.reshape(60000,28,28,3) 
    X_test = X_test.reshape(10000,28,28,3)
    y_train = to_categorical(y_train)
    y_test = to_categorical(y_test)
    
    print(y_train[0])
    '''
    softmax layer -> output=10개의 노드. 각각이 0부터 9까지 숫자를 대표하는 클래스 
    
    이를 위해서 y값을 one-hot encoding 표현법으로 변환
    0: 1,0,0,0,0,0,0,0,0,0
    1: 0,1,0,0,0,0,0,0,0,0
    ...
    5: 0,0,0,0,0,1,0,0,0,0
    '''
    
    y_train = to_categorical(y_train)
    y_test = to_categorical(y_test)
    
    print(y_train[0])
    
    
    model = Sequential([
                #고정
                Input(shape=(300,300,3), name='input_layer'),
                
                # n_filters * (filter_size + 1) = 32*(9+1) = 320
                Conv2D(32, kernel_size=3, activation='relu', name='conv_layer1'),
                
                
                #Dropout(0.5)
                MaxPooling2D(pool_size=2),
                #Conv2D(64, kernel_size=3, activation='relu', name='conv_layer1'),
                Flatten(),
                #Dense(20, activation='softmax', name='output_layer')
        
        
                #고정
                Dense(3, activation='softmax', name='output_layer')
            ])

    model.summary()    
    
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    
    history = model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=15, epochs=3)
    plot_loss_curve(history.history)
    print(history.history)
    print("train loss=", history.history['loss'][-1])
    print("validation loss=", history.history['val_loss'][-1])    
    
    model.save('mnist.model')
    
    return model



def train_mnist_model():
    (X_train, y_train), (X_test, y_test) = ************데이터 어떻게 불러올거야? 
    X_train = X_train.reshape(60000,28,28,3) 
    X_test = X_test.reshape(10000,28,28,3)
    y_train = to_categorical(y_train)
    y_test = to_categorical(y_test)
#     print(y_train[1563])
    
    
    #옵티마이저, loss , 변경해보기
    model.compile(optimizer= 'adam', loss='categorical_crossentropy',metrics=['accuracy'])
    history = model.fit(X_train,y_train, validation_data=(X_test, y_test), batch_size=20, epochs = 3)
    
    plot_loss_curve(history.history)
    print(history.history)
    print('train loss =', history.history['loss'][-1])
    print('validation loss =', history.history['val_loss'][-1])

    model.save('model-201814132')
    return model


예측


In [ ]:

def predict_image_sample(model,X_test, y_test, test_id= -1 ):
    if test_id <0 :
        from random import randrange
        test_sample_id = randrange(10002)
    else:
        test_sample_id = test_id
    
    test_image =X_test[test_sample_id]
#     plt.imshow(test_image, cmap = 'gray')
    
    test_image = test_image.reshape(1,28,28,3)
    
    y_actual = y_test[test_sample_id]
    print('y_actual number = ', y_actual)
    
    y_pred = model.predict(test_image)
    print("y_pred = ", y_pred)
    y_pred_num = np.argmax(y_pred, axis = 1)[0]
    print('y_pred number = ', y_pred)
    return y_actual , y_pred_num
    


실행

In [ ]:
    
if __name__ == '__main__' :
    all, n = 0,0
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    model = load_model('mnist.model')
#     predict_image_sample(model,X_test, y_test)
    
    for i in range(500):
        y_actual , y_pred_num = predict_image_sample(model,X_test, y_test,test_id = i)
        if y_actual == y_pred_num:
            n += 1 
        else : pass
print('정확도 = ', (n/i)*100,'\n',i,' '*10,n)