In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint

import pandas as pd 
import os
import matplotlib.pyplot as plt
import cv2
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Dense, Flatten
from keras.utils import to_categorical

from keras.models import Sequential,load_model

from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
np.random.seed(1)


train_datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    validation_split = 0.2,
    rotation_range=10,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.7,
    rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        './images2/train',
        target_size = (300,300),
        batch_size=100,
        #color_mode ='rgb',
        classes = ['food','interior', 'exterior'],
        shuffle =True,
        seed = 42,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        './images2/test',
        classes = ['food','interior', 'exterior'],
        target_size=(300,300),
        batch_size=20,
#         color_mode ='rgb',
        shuffle =True,
        seed = 42,
        class_mode='categorical')

ERROR! Session/line number was not unique in database. History logging moved to new session 314
Found 36000 images belonging to 3 classes.
Found 9000 images belonging to 3 classes.


In [5]:
model = Sequential()
model.add(Conv2D(32, kernel_size=3,
                 activation='selu',
                 input_shape=(300,300,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(32, 3, activation='selu'))
model.add(MaxPooling2D(pool_size=2))
# model.add(Conv2D(32, 3, activation='selu'))
# model.add(MaxPooling2D(pool_size=2))
model.add(Flatten())
# model.add(Dense(8, activation='selu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

# 3. 모델 학습과정 설정 및 요약
model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 4. 모델 학습시키기
model.fit_generator(
    train_generator,
    steps_per_epoch=10,
    epochs=5,
    validation_data=test_generator,
    validation_steps=10)

model.save('model-17')

# 5. 모델 평가하기
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 6. 모델 사용하기
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 298, 298, 32)      896       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 149, 149, 32)      0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 147, 147, 32)      9248      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 73, 73, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 170528)            0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1705290   
_________________________________________________________________
dense_5 (Dense)              (None, 3)                

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


INFO:tensorflow:Assets written to: model-17\assets


INFO:tensorflow:Assets written to: model-17\assets


-- Evaluate --
Instructions for updating:
Please use Model.evaluate, which supports generators.


Instructions for updating:
Please use Model.evaluate, which supports generators.


accuracy: 70.00%
-- Predict --
Instructions for updating:
Please use Model.predict, which supports generators.


Instructions for updating:
Please use Model.predict, which supports generators.


{'food': 0, 'interior': 1, 'exterior': 2}
[[0.744 0.244 0.013]
 [0.910 0.089 0.001]
 [0.071 0.276 0.653]
 [0.799 0.194 0.007]
 [0.385 0.391 0.224]
 [0.788 0.206 0.006]
 [0.501 0.410 0.088]
 [0.837 0.160 0.003]
 [0.406 0.443 0.151]
 [0.944 0.056 0.000]
 [0.275 0.431 0.294]
 [0.919 0.080 0.000]
 [0.381 0.388 0.231]
 [0.910 0.090 0.001]
 [0.443 0.415 0.142]
 [0.172 0.400 0.428]
 [0.892 0.107 0.001]
 [0.657 0.309 0.034]
 [0.913 0.087 0.001]
 [0.952 0.047 0.000]
 [0.076 0.285 0.639]
 [0.314 0.431 0.255]
 [0.642 0.328 0.030]
 [0.326 0.455 0.219]
 [0.586 0.366 0.048]
 [0.096 0.297 0.606]
 [0.860 0.137 0.002]
 [0.761 0.226 0.013]
 [0.524 0.400 0.076]
 [0.467 0.409 0.124]
 [0.613 0.348 0.039]
 [0.233 0.444 0.323]
 [0.645 0.317 0.039]
 [0.689 0.288 0.023]
 [0.439 0.425 0.137]
 [0.283 0.416 0.301]
 [0.381 0.444 0.175]
 [0.877 0.121 0.002]
 [0.108 0.326 0.566]
 [0.269 0.436 0.296]
 [0.493 0.416 0.092]
 [0.924 0.076 0.000]
 [0.592 0.354 0.054]
 [0.086 0.290 0.624]
 [0.167 0.400 0.433]
 [0.683 0.294